name: Deploy to EC2

on:
  push:
    branches:
      - master  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-51-20-81-225.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            # Navigate to your project directory
            cd ~/test_app/node-docker-app
            
            # Pull latest changes
            git pull
            
            # Stop and remove ALL containers (in case any are stuck)
            docker stop $(docker ps -a -q) || true
            docker rm $(docker ps -a -q) || true
            
            # Remove old images to free up space
            docker system prune -f
            
            # Build new image
            docker build -t node-hello-world .
            
            # Make sure port 3000 is free
            sudo lsof -t -i:3000 | xargs -r sudo kill -9 || true
            
            # Run new container with restart policy
            docker run -d --name node-app --restart unless-stopped -p 3000:3000 node-hello-world

            # Verify the container is running
            docker ps | grep node-app